- hosts: 192.168.7.2
  vars:
      my_hostname: bbb

  tasks:

  - name: "Ensure avahi is installed"
    apt: name={{ item }} state=present
    with_items:
      - avahi-daemon
      - avahi-utils
      - avahi-dnsconfd
      - libavahi-core-dev
    tags:
      - avahi
      - pkgs

  - name: "Ensure avahi allow interface is eth0"
    lineinfile:
        dest=/etc/avahi/avahi-daemon.conf
        regexp="^#?allow-interfaces="
        line="allow-interfaces=eth0" 
        state=present

  - name: "Ensure avahi deny interface is usb0"
    lineinfile:
        dest=/etc/avahi/avahi-daemon.conf
        regexp="^#?deny-interfaces="
        line="deny-interfaces=usb0"
        state=present

  - name: "Change beaglebone hostname"
    hostname: name={{my_hostname}}
